{% set version = "2.0.3" %}

package:
  name: openalea.mtg
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    # - openalea.deploy
  run:
    - python
    #- openalea.deploy
    # - openalea.core
    - numpy
    - matplotlib
    - pandas
    - openalea.plantgl

test:
  requires:
    - pytest
  imports:
    - openalea.mtg
   source_files:
     - test/**
     - test/data/**
   commands:
     - cd test
     - pytest -v --ignore=test_aml.py --ignore=test_parsing_mtg.py --ignore=test_parsing_axialtree.py  --ignore=test_stat.py

about:
  home: http://openalea.gforge.inria.fr/
  license: CeCILL_C
  summary: OpenAlea.MTG implements Multiscale Tree Graph datastructure and interfaces

