{% set data = load_setup_py_data() %}

package:
  name: openalea.mtg
  version: {{ data.get('version') }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 1
  script: python setup.py install

requirements:
  build:
    - python
    # - openalea.deploy
  run:
    - python
    - openalea.plantgl
    - numpy
    - matplotlib
    - pandas
    # - openalea.deploy
    # - openalea.core

test:
  requires:
    - pytest
    - path.py
    - openalea.lpy
  imports:
    - openalea.mtg
  source_files:
    - test/**
    - test/data/**
  commands:
    - cd test
    - pytest -v --ignore=test_aml.py  --ignore=test_stat.py

about:
  home: http://openalea.gforge.inria.fr/
  license: CeCILL_C
  summary: OpenAlea.MTG implements Multiscale Tree Graph datastructure and interfaces

