{% set version = "2.0.2" %}

package:
  name: openalea.mtg
  version: {{ version }}

source:
  path: ..

build:
  preserve_egg_dir: True
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - openalea.deploy
  run:
    - python
    - openalea.deploy
    # - openalea.core
    - numpy
    - matplotlib
    - pandas
    - openalea.plantgl

test:
  imports:
    - openalea.mtg

about:
  home: http://openalea.gforge.inria.fr/
  license: CeCILL_C
  summary: OpenAlea.MTG implements Multiscale Tree Graph datastructure and interfaces

